download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/devsec-hardening-9.0.1.tar.gz
format_version: 1.0.0
name: hardening
namespace: devsec
server: https://galaxy.ansible.com/api/
signatures: []
version: 9.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/devsec/hardening/versions/9.0.1/
