---

- name: "1.1.9 | PATCH | Disable Automounting"
  ansible.builtin.service:
      name: autofs
      enabled: false
  when:
      - not rhel8cis_allow_autofs
      - "'autofs' in ansible_facts.packages"
      - rhel8cis_rule_1_1_9
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - mounts
      - automounting
      - rule_1.1.9
