# - name: Find /etc/sudoers.d/ files
#   ansible.builtin.find:
#     paths:
#     - /etc/sudoers.d/
#   register: sudoers
#   tags:
#   - NIST-800-53-CM-6(a)
#   - NIST-800-53-IA-11
#   - PCI-DSSv4-2.2.6
#   - low_complexity
#   - low_disruption
#   - medium_severity
#   - no_reboot_needed
#   - restrict_strategy
#   - sudo_require_authentication

# - name: Remove lines containing NOPASSWD from sudoers files
#   ansible.builtin.replace:
#     regexp: (^(?!#).*[\s]+NOPASSWD[\s]*\:.*$)
#     replace: '# \g<1>'
#     path: '{{ item.path }}'
#     validate: /usr/sbin/visudo -cf %s
#   with_items:
#   - path: /etc/sudoers
#   - '{{ sudoers.files }}'
#   tags:
#   - NIST-800-53-CM-6(a)
#   - NIST-800-53-IA-11
#   - PCI-DSSv4-2.2.6
#   - low_complexity
#   - low_disruption
#   - medium_severity
#   - no_reboot_needed
#   - restrict_strategy
#   - sudo_require_authentication

# - name: Find /etc/sudoers.d/ files
#   ansible.builtin.find:
#     paths:
#     - /etc/sudoers.d/
#   register: sudoers
#   tags:
#   - NIST-800-53-CM-6(a)
#   - NIST-800-53-IA-11
#   - PCI-DSSv4-2.2.6
#   - low_complexity
#   - low_disruption
#   - medium_severity
#   - no_reboot_needed
#   - restrict_strategy
#   - sudo_require_authentication

# - name: Remove lines containing !authenticate from sudoers files
#   ansible.builtin.replace:
#     regexp: (^(?!#).*[\s]+\!authenticate.*$)
#     replace: '# \g<1>'
#     path: '{{ item.path }}'
#     validate: /usr/sbin/visudo -cf %s
#   with_items:
#   - path: /etc/sudoers
#   - '{{ sudoers.files }}'
#   tags:
#   - NIST-800-53-CM-6(a)
#   - NIST-800-53-IA-11
#   - PCI-DSSv4-2.2.6
#   - low_complexity
#   - low_disruption
#   - medium_severity
#   - no_reboot_needed
#   - restrict_strategy
#   - sudo_require_authentication