---
# Preliminary tasks that should always be run
- name: "PRELIM | AUDIT | Set facts based on boot type"
  tags:
      - always
  block:
      - name: "PRELIM | AUDIT | Check whether machine is UEFI-based"
        ansible.builtin.stat:
            path: /sys/firmware/efi
        register: discovered_efi_boot

      - name: "PRELIM | AUDIT | set legacy boot and grub path fact | Bios"
        when: not discovered_efi_boot.stat.exists
        ansible.builtin.set_fact:
            rhel8cis_legacy_boot: true
            grub2_path: /etc/grub2.cfg
            rhel8cis_boot_path: /boot/grub2/

      - name: "PRELIM | AUDIT | set grub fact | UEFI"
        when: discovered_efi_boot.stat.exists
        ansible.builtin.set_fact:
            grub2_path: /etc/grub2-efi.cfg
            rhel8cis_boot_path: "/boot/efi/EFI/{{ansible_facts.distribution | lower }}/"

- name: Include audit specific variables
  when:
      - run_audit or audit_only
      - setup_audit
  tags:
      - setup_audit
      - run_audit
  ansible.builtin.include_vars:
      file: audit.yml

- name: Include pre-remediation audit tasks
  when:
      - run_audit or audit_only
      - setup_audit
  tags:
      - run_audit
  ansible.builtin.import_tasks:
      file: pre_remediation_audit.yml

