---
- name: Security Remediate Phase
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Rocky8 OS
      include_role:
        name: RHEL8-CIS-Remediate
      when: ansible_distribution == "Rocky" and ansible_distribution_major_version == '8'

    - name: Rocky9 OS
      include_role:
        name: RHEL9-CIS-Remediate
      when: ansible_distribution == "Rocky" and ansible_distribution_major_version == '9'


    - name: Debian12 OS
      include_role:
        name: DEBIAN12-CIS-Remediate
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == '12'

    - name: Ubuntu22 OS
      include_role:
        name: UBUNTU22-CIS-Remediate
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '22'