---

# Preliminary tasks that should always be run
# List users in order to look files inside each home directory

- name: PRELIM | Include audit specific variables
  when:
      - run_audit or audit_only
      - setup_audit
  tags:
      - setup_audit
      - run_audit
  ansible.builtin.include_vars: audit.yml

- name: PRELIM | Include pre-remediation audit tasks
  when:
      - run_audit or audit_only
      - setup_audit
  tags:
      - run_audit
  ansible.builtin.import_tasks: pre_remediation_audit.yml

